In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in ./anaconda3/lib/python3.11/site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (1.11.1)
Requirement already satisfied: numpy>=1.16.2 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: pandas>=0.24.2 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (2.0.3)
Requirement already satisfied: scikit-learn>=1.0.2 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (3.7.2)
Requirement already satisfied: joblib>=0.13.2 in ./anaconda3/lib/python3.11/site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (10.2.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./anaconda3/lib/python3.11/site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.11/site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/lib/python3.11/site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/lib/python3.11/site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import pandas as pd

In [3]:
#import all required class from mlxtend library for market basket analysis 
from mlxtend.preprocessing import TransactionEncoder #required to transform transaction data into required format
from mlxtend.frequent_patterns import apriori #required to generate frequent itemset
from mlxtend.frequent_patterns import association_rules #to generate rules

In [4]:
sample_data=[['milk','bread','water'],['coffee','sugar','water'],['burgers','egg','bread']]

In [5]:
sample_data

[['milk', 'bread', 'water'],
 ['coffee', 'sugar', 'water'],
 ['burgers', 'egg', 'bread']]

In [6]:
transaction_encoder = TransactionEncoder()

In [7]:
transaction_array = transaction_encoder.fit(sample_data).transform(sample_data)

In [8]:
transaction_array

array([[ True, False, False, False,  True, False,  True],
       [False, False,  True, False, False,  True,  True],
       [ True,  True, False,  True, False, False, False]])

In [9]:
transaction_data=pd.DataFrame(transaction_array,columns=transaction_encoder.columns_)
transaction_data

   bread  burgers  coffee    egg   milk  sugar  water
0   True    False   False  False   True  False   True
1  False    False    True  False  False   True   True
2   True     True   False   True  False  False  False

In [10]:
frequent_itemset=apriori(transaction_data,min_support=0.3,use_colnames=True)

In [11]:
frequent_itemset

     support                itemsets
0   0.666667                 (bread)
1   0.333333               (burgers)
2   0.333333                (coffee)
3   0.333333                   (egg)
4   0.333333                  (milk)
5   0.333333                 (sugar)
6   0.666667                 (water)
7   0.333333        (burgers, bread)
8   0.333333            (egg, bread)
9   0.333333           (milk, bread)
10  0.333333          (water, bread)
11  0.333333          (burgers, egg)
12  0.333333         (sugar, coffee)
13  0.333333         (water, coffee)
14  0.333333           (water, milk)
15  0.333333          (water, sugar)
16  0.333333   (burgers, egg, bread)
17  0.333333    (water, milk, bread)
18  0.333333  (water, sugar, coffee)

In [12]:
rules=association_rules(frequent_itemset, metric='confidence' ,min_threshold=0.6)

In [13]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(burgers),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
1,(egg),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
2,(milk),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
3,(burgers),(egg),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
4,(egg),(burgers),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
5,(sugar),(coffee),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
6,(coffee),(sugar),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
7,(coffee),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
8,(milk),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
9,(sugar),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
10,"(burgers, egg)",(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
11,"(burgers, bread)",(egg),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
12,"(egg, bread)",(burgers),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
13,(burgers),"(egg, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
14,(egg),"(burgers, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
15,"(water, milk)",(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
16,"(water, bread)",(milk),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
17,"(milk, bread)",(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
18,(milk),"(water, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
19,"(water, sugar)",(coffee),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
20,"(water, coffee)",(sugar),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
21,"(sugar, coffee)",(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
22,(sugar),"(water, coffee)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
23,(coffee),"(water, sugar)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0

In [14]:
rules[rules['lift']>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(burgers),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
1,(egg),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
2,(milk),(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
3,(burgers),(egg),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
4,(egg),(burgers),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
5,(sugar),(coffee),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
6,(coffee),(sugar),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
7,(coffee),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
8,(milk),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
9,(sugar),(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
10,"(burgers, egg)",(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
11,"(burgers, bread)",(egg),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
12,"(egg, bread)",(burgers),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
13,(burgers),"(egg, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
14,(egg),"(burgers, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
15,"(water, milk)",(bread),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
16,"(water, bread)",(milk),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
17,"(milk, bread)",(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
18,(milk),"(water, bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
19,"(water, sugar)",(coffee),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
20,"(water, coffee)",(sugar),0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
21,"(sugar, coffee)",(water),0.333333,0.666667,0.333333,1.0,1.5,0.111111,inf,0.5
22,(sugar),"(water, coffee)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0
23,(coffee),"(water, sugar)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf,1.0